version: '3.8'

services:
  app:
    container_name: pizzeria_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pizzeria
    depends_on:
      - db

  db:
    container_name: pizzeria_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pizzeria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
